export default {
    "login": "NishidhJain",
    "id": 61869195,
    "node_id": "MDQ6VXNlcjYxODY5MTk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/61869195?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NishidhJain",
    "html_url": "https://github.com/NishidhJain",
    "followers_url": "https://api.github.com/users/NishidhJain/followers",
    "following_url": "https://api.github.com/users/NishidhJain/following{/other_user}",
    "gists_url": "https://api.github.com/users/NishidhJain/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NishidhJain/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NishidhJain/subscriptions",
    "organizations_url": "https://api.github.com/users/NishidhJain/orgs",
    "repos_url": "https://api.github.com/users/NishidhJain/repos",
    "events_url": "https://api.github.com/users/NishidhJain/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NishidhJain/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Nishidh Jain",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 8,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2020-03-06T10:11:26Z",
    "updated_at": "2021-01-29T16:36:52Z"
}